### PR TITLE
postcard template

### PR DESCRIPTION
**Pull request by JahnabDutta**
-added check on body/image
-image rendering on postcard

### CODE REVIEW

**Comment by imraghav20** [comment]
Please address the following issues:
1. Allow to add multiple images.
2. New line is not showing in preview on hitting enter.
3. The site is not mobile friendly.

**Comment by JahnabDutta** [comment]
added responsiveness and multiple image uploading option

**Comment by JahnabDutta** [comment]
added email validation

**Comment by imraghav20** [comment]
lgtm

**Pull request merged**
